# Generated by Django 4.2.5 on 2023-10-13 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Report_Viewer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='mrn',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
