# Generated by Django 4.2.5 on 2023-10-13 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Report_Viewer', '0002_patient_mrn'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='dateOfBirth',
            field=models.DateField(blank=True, null=True),
        ),
    ]
