# Generated by Django 4.2.5 on 2023-10-13 18:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Report_Viewer', '0003_patient_dateofbirth'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visitIDNumber', models.IntegerField(blank=True, null=True)),
                ('visitCount', models.IntegerField(blank=True, null=True)),
                ('visitDate', models.DateField(blank=True, null=True)),
                ('patientNumber', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='visit', to='Report_Viewer.patient')),
            ],
            options={
                'verbose_name_plural': 'Visits',
            },
        ),
    ]
