# Generated by Django 4.2.5 on 2023-10-13 18:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Report_Viewer', '0004_visit'),
    ]

    operations = [
        migrations.RenameField(
            model_name='visit',
            old_name='visitIDNumber',
            new_name='visitID',
        ),
        migrations.CreateModel(
            name='ReportData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reportDataID', models.IntegerField(blank=True, null=True)),
                ('reportImage', models.ImageField(blank=True, null=True, upload_to=None)),
                ('visitNumber', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='reportdata', to='Report_Viewer.visit')),
            ],
            options={
                'verbose_name_plural': 'Report Data',
            },
        ),
        migrations.CreateModel(
            name='ImageData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imageDataID', models.IntegerField(blank=True, null=True)),
                ('whichEye', models.CharField(blank=True, max_length=100, null=True)),
                ('fullImage', models.ImageField(blank=True, null=True, upload_to=None)),
                ('retinalImage', models.ImageField(blank=True, null=True, upload_to=None)),
                ('thicknessImage', models.ImageField(blank=True, null=True, upload_to=None)),
                ('enfaceImage', models.ImageField(blank=True, null=True, upload_to=None)),
                ('visitNumber', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='imagedata', to='Report_Viewer.visit')),
            ],
            options={
                'verbose_name_plural': 'Image Data',
            },
        ),
    ]
