# Generated by Django 4.2.5 on 2023-10-13 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Report_Viewer', '0005_rename_visitidnumber_visit_visitid_reportdata_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagedata',
            name='imageDataID',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='reportdata',
            name='reportDataID',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='visit',
            name='visitID',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
